/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reseau_social.gui;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import reseau_social.Moderateur_1;
import reseau_social.Moderateur_2;
import reseau_social.Person;
import reseau_social.User;
import reseau_social.UserList;
import reseau_social.company.Ceo;
import reseau_social.company.Employee;
import reseau_social.database.Users;

/**
 *
 * @author adrien
 */
public class Inscritpion extends javax.swing.JFrame {

    /**
     * Creates new form Inscritpion
     */
    public Inscritpion() {
        initComponents();
        this.setTitle("Inscription");
        this.setSize(650, 450);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        niv1.setVisible(false);
        niv2.setVisible(false);
        inputPay.setVisible(false);
        pay.setVisible(false);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        validate = new javax.swing.JButton();
        userType = new javax.swing.JComboBox<>();
        lastnameInput = new javax.swing.JTextField();
        nameInput = new javax.swing.JTextField();
        yearOfBirthInput = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        lastname = new javax.swing.JLabel();
        yearOfBirth = new javax.swing.JLabel();
        niv1 = new javax.swing.JRadioButton();
        niv2 = new javax.swing.JRadioButton();
        pay = new javax.swing.JLabel();
        inputPay = new javax.swing.JTextField();
        back = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Inscription");

        validate.setText("valider");
        validate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateActionPerformed(evt);
            }
        });

        userType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Utilisteur", "Moderateur", "Directeur" }));
        userType.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                userTypeComponentHidden(evt);
            }
        });
        userType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTypeActionPerformed(evt);
            }
        });

        name.setText("Prénom");

        lastname.setText("Nom");

        yearOfBirth.setText("Année de naissance");

        buttonGroup1.add(niv1);
        niv1.setText("Niv 1");

        buttonGroup1.add(niv2);
        niv2.setText("Niv 2");
        niv2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                niv2ActionPerformed(evt);
            }
        });

        pay.setText("Salaire");

        back.setText("retour");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(yearOfBirth)
                    .addComponent(lastname)
                    .addComponent(name)
                    .addComponent(pay))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lastnameInput)
                        .addComponent(yearOfBirthInput)
                        .addComponent(nameInput)
                        .addComponent(niv2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(niv1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(userType, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inputPay, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(validate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(back)))
                .addContainerGap(262, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearOfBirthInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearOfBirth))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(niv1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(niv2)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pay))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(validate)
                    .addComponent(back))
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void userTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTypeActionPerformed
        // TODO add your handling code here:
        System.out.println(userType.getSelectedItem());
        if (userType.getSelectedItem() == "Directeur") {
            niv1.setVisible(false);
            niv2.setVisible(false);
            inputPay.setVisible(true);
            pay.setVisible(true);
        } else if (userType.getSelectedItem() == "Moderateur") {
            inputPay.setVisible(false);
            pay.setVisible(false);
            niv1.setVisible(true);
            niv2.setVisible(true);
        } else {
            niv1.setVisible(false);
            niv2.setVisible(false);
            inputPay.setVisible(false);
            pay.setVisible(false);
        }
    }//GEN-LAST:event_userTypeActionPerformed

    private void niv2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_niv2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_niv2ActionPerformed

    private void userTypeComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_userTypeComponentHidden
        // TODO add your handling code here:
        
    }//GEN-LAST:event_userTypeComponentHidden

    private void validateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateActionPerformed
        // TODO add your handling code here:
        String message1 = "Attention";
        String message2 = "Une erreure est survenue, veuillez recommencer !";
        try {
        int year = Integer.parseInt(yearOfBirthInput.getText()); 
        String status = (String) userType.getSelectedItem();
        if (status.equalsIgnoreCase("Moderateur")) {
            
            System.out.println(buttonGroup1.getSelection().toString());
            String bouton = buttonGroup1.getElements().nextElement().getText();
            status = status + "_" + bouton;         
        }
              
        Users.createtUser(nameInput.getText(), lastnameInput.getText(), year, status);
        message1 = "Bravo";
        message2 = "Votre inscritpion est validée !";
        
        
        } catch (Exception e) {
            JOptionPane jop3 = new JOptionPane();
            jop3.showMessageDialog(null, "Veuillez rentrer une date valide", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        JOptionPane info = new JOptionPane();
        info.showMessageDialog(null, message2, message1, JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_validateActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        IndexJFrame wind = new IndexJFrame(); 
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inscritpion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inscritpion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inscritpion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inscritpion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inscritpion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField inputPay;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lastname;
    private javax.swing.JTextField lastnameInput;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nameInput;
    private javax.swing.JRadioButton niv1;
    private javax.swing.JRadioButton niv2;
    private javax.swing.JLabel pay;
    private javax.swing.JComboBox<String> userType;
    private javax.swing.JButton validate;
    private javax.swing.JLabel yearOfBirth;
    private javax.swing.JTextField yearOfBirthInput;
    // End of variables declaration//GEN-END:variables
}
