FROM debian:jessie

MAINTAINER adrien juhem <adrien.juhem@gmail.com>

ENV CATALINA_HOME /usr/local/tomcat
ENV PATH $CATALINA_HOME/bin:$PATH

RUN mkdir -p "$CATALINA_HOME"
WORKDIR $CATALINA_HOME

RUN apt-get update && apt-get install tomcat8 && apt-get install haveged



EXPOSE 8081

CMD ["catalina.sh", "run"]
